In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from joblib import dump, load
import matplotlib.pyplot as plt
import csv
import torch
import torch.nn as nn
import torch.optim as optim
from data_loader import CustomSignalData, CustomSignalData1
from torch.autograd import Variable
from encoder import Encoder as E
from helpers import set_cmd_cb, rms_formuula, get_data, get_all_data, get_shift_data, get_operators, plot_cfs_mat, roll_data


/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
DEVICE = torch.device("cpu")
def getFeatureMatrix(rawDataMatrix, windowLength, windowOverlap):
    rms = lambda sig: np.sqrt(np.mean(sig**2))
    nChannels,nSamples = rawDataMatrix.shape    
    I = int(np.floor(nSamples/(windowLength-windowOverlap)))
    featMatrix = np.zeros([nChannels, I])
    for channel in range(nChannels):
        for i in range (I):
            wdwStrtIdx=i*(windowLength-windowOverlap)
            sigWin = rawDataMatrix[channel][wdwStrtIdx:(wdwStrtIdx+windowLength-1)] 
            featMatrix[channel, i] = rms(sigWin)
    featMatrixData = np.array(featMatrix)
    return featMatrixData

class FFNN(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(FFNN, self).__init__()
        self.encoder = torch.nn.Sequential(
            torch.nn.Linear(inputSize, 9, bias=False),
            torch.nn.Sigmoid()
        )
        self.classifer = torch.nn.Sequential(
            torch.nn.Linear(9, outputSize, bias=False),
            # torch.nn.Softmax(dim=1)
        )

    def forward(self, x, encoder=None):
        if not encoder:
            encoder = self.encoder
        z = encoder(x)
        class_z = self.classifer(z)

        return class_z

class Operator(nn.Module):
    def __init__(self, in_features, n_rotations):
        super(Operator, self).__init__()
        """
        Args:
          in_features (int): Number of input features which should be equal to xsize.
          out_features (out): Number of output features which should be equal to ysize.
        """
        self.in_features = in_features
        self.core = torch.nn.Parameter(torch.zeros(3*self.in_features**2)- 0*torch.diag(torch.rand(3*self.in_features**2)/10))
        self.core.requires_grad = True
        self.n_rotations = n_rotations
        
    def rotate_batch(self, x, d, out_features):
      rotated = torch.empty(x.shape[0], 3*out_features*out_features, device=DEVICE)
      phies = [torch.linalg.matrix_power(self.core,i).to(DEVICE) for i in range (0,self.n_rotations+0)]
      for i in range (x.shape[0]):
        rotated[i] = phies[(d[i]+0)%4].matmul(x[i]) 
      return rotated

    def forward(self, x, d):
        """
        Args:
          x of shape (batch_size, 3, xsize, xsize): Inputs.
        
        Returns:
          y of shape (batch_size, 3*xsize^2): Outputs.
        """
        z = self.rotate_batch(x, d, self.in_features)
        return z
def get_tensor(arr):
    return torch.tensor(arr, device=DEVICE,dtype=torch.float )

def rotate_batch(x, d, out_features):
    M = torch.diag(torch.ones(8)).roll(-1,1)
    used_bases = [torch.linalg.matrix_power(M,i).to(DEVICE) for i in range (8)]
    rotated = torch.empty(x.shape, device=DEVICE)
    for i in range (x.shape[0]):
        rotated[i] = used_bases[d[i]].matmul(x[i]) 
    return rotated

def clf_acc(model, loader, masks = None, encoder = None):
    model.eval()
    correct = 0
    iter = 0
    with torch.no_grad():
        for inputs, labels,_,_ in loader:
            inputs = inputs.to(DEVICE)
            if masks is not None:
                inputs = inputs * masks[:inputs.size()[0]]
            labels = labels.to(DEVICE)
            labels = labels.flatten()
            if encoder:
                pred = model(inputs, encoder)
            else:
                pred = model(inputs)
            correct += (1-torch.abs(torch.sign(torch.argmax(pred,dim = 1)- labels))).mean().item()
            iter += 1
    return correct/iter

def compute_accuracy(a, b, loader):
    a.eval()
    b.eval()
    
    correct = 0
    iter = 0
    
    with torch.no_grad():
        for inputs1, inputs2, shift1, shift2, labels, _ in loader:
            inputs1 = inputs1.to(DEVICE)
            inputs2 = inputs2.to(DEVICE)
            shift1 = -shift1.int().flatten().to(DEVICE)
            shift2 = -shift2.int().flatten().to(DEVICE)
            labels = labels.flatten().to(DEVICE)
            # zero the parameter gradients
            optimizer.zero_grad()
            
            # forward + backward + optimize
            y1 = a(inputs1)
            y_tr_est1 = rotate_batch(y1,shift1,6)
            y_tr1 = b(y_tr_est1)

            y2 = a(inputs2)
            y_tr_est2 = rotate_batch(y2,shift1,6)
            y_tr2 = b(y_tr_est2)

            correct += (1-torch.abs(torch.sign(torch.argmax(y_tr1,dim = 1)- labels))).mean().item() + \
                    (1-torch.abs(torch.sign(torch.argmax(y_tr2,dim = 1)- labels))).mean().item()
            iter += 1
    return correct * 0.5 / iter

In [3]:
subject = '22'
No_shift = '8'

Fs = 1000
windowLength = int(np.floor(0.1*Fs))  #160ms
windowOverlap =  int(np.floor(50/100 * windowLength))

# X_train = np.zeros([0,8])
# y_train= np.zeros([0])
X_test = np.zeros([0,8])
y_test = np.zeros([0])

for shift in range(0,int(No_shift)): 
    for files in sorted(os.listdir(f'Subject_{subject}/Shift_{shift}/')):
        _, class_,_, rep_ = files.split('_')
        if int(class_) in [1,2,3,4,5,6,7,8,9]:
            df = pd.read_csv(f'Subject_{subject}/Shift_{shift}/{files}',skiprows=0,sep=' ',header=None)
            data_arr = np.stack([np.array(df.T[i::8]).T.flatten().astype('float32') for i in range (8)])
            data_arr -= 121
            data_arr /= 255.0
            feaData = getFeatureMatrix(data_arr, windowLength, windowOverlap)
            
            if not class_.startswith('9'):
                rms_feature = feaData.sum(0)
                baseline = 2*rms_feature[-50:].mean()
                start_ = np.argmax(rms_feature[::1]>baseline)
                end_  = -np.argmax(rms_feature[::-1]>baseline)
                feaData = feaData.T[start_:end_]
            else:
                feaData = feaData.T

            # if rep_.startswith('2'):
            #     X_test = np.concatenate([X_test,feaData])
            #     y_test = np.concatenate([y_test,np.ones_like(feaData)[:,0]*int(class_)-1])
            
            X_test = np.concatenate([X_test,feaData])
            y_test= np.concatenate([y_test,np.ones_like(feaData)[:,0]*int(class_)-1])


In [4]:
print(X_test)
print(X_test.shape)
print(y_test)
print(y_test.shape)

[[0.00618173 0.00219444 0.00343597 ... 0.02130139 0.01734183 0.00831423]
 [0.00623178 0.0024296  0.00369729 ... 0.02960195 0.01487295 0.0117581 ]
 [0.00609314 0.00215875 0.0031776  ... 0.03120872 0.0161113  0.01154479]
 ...
 [0.00468006 0.0011824  0.00305294 ... 0.0031034  0.00193085 0.0032501 ]
 [0.00501649 0.00124636 0.00320195 ... 0.0031776  0.00208555 0.00336747]
 [0.00518775 0.00129694 0.00313879 ... 0.00321443 0.00202113 0.00346621]]
(37757, 8)
[0. 0. 0. ... 8. 8. 8.]
(37757,)


In [5]:
# all_X_train, all_y_train, all_shift_train = get_all_data(X_train, y_train)
all_X_test, all_y_test, all_shift_test = get_all_data(X_test, y_test)

# all_X1_train, all_X2_train, all_shift_1_train, all_shift_2_train, all_y_shift_train = get_shift_data(all_X_train, all_shift_train, all_y_train)
all_X1_test, all_X2_test, all_shift_1_test, all_shift_2_test, all_y_shift_test = get_shift_data(all_X_test, all_shift_test, all_y_test)

# Data loader
# traindataset = CustomSignalData(get_tensor(X_train), get_tensor(y_train))
testdataset = CustomSignalData(get_tensor(X_test), get_tensor(y_test))

# trainloader = torch.utils.data.DataLoader(traindataset, batch_size = 1, shuffle=True)
testloader = torch.utils.data.DataLoader(testdataset, batch_size=24, shuffle=True)

# all_train_dataset = CustomSignalData(get_tensor(all_X_train), get_tensor(all_y_train))
# alltrainloader = torch.utils.data.DataLoader(all_train_dataset, batch_size = 102, shuffle=True)
all_test_dataset = CustomSignalData(get_tensor(all_X_test), get_tensor(all_y_test))
alltestloader = torch.utils.data.DataLoader(all_test_dataset, batch_size = 102, shuffle=True)

# triplet_train_dataset = CustomSignalData1(get_tensor(all_X1_train), get_tensor(all_X2_train), get_tensor(all_shift_1_train), get_tensor(all_shift_2_train), get_tensor(all_y_shift_train))
# triplettrainloader = torch.utils.data.DataLoader(triplet_train_dataset, batch_size = 102, shuffle=True)
triplet_test_dataset = CustomSignalData1(get_tensor(all_X1_test), get_tensor(all_X2_test), get_tensor(all_shift_1_test), get_tensor(all_shift_2_test), get_tensor(all_y_shift_test))
triplettestloader = torch.utils.data.DataLoader(triplet_test_dataset, batch_size = 102, shuffle=True)


LOAD LEARNING MODEL

In [6]:
logRegres  = load('LogisticRegression1.joblib')

DEVICE = torch.device("cpu") # operations is in CPU or GPU.
M = torch.diag(torch.ones(8)).roll(-1,1) # Create a diagnoise matrix then shift it to the right
used_bases = [torch.linalg.matrix_power(M,i).to(DEVICE) for i in range (8)] #

N_points = 1000

TEST ACCURACY OF LOGISTIC rEGRESSION

In [7]:
accuracies_LosReg_shift = []
for i in range (-4, 4):
    X_test_shift = roll_data(X_test, i)
    accuracies_LosReg_shift.append(logRegres.score(X_test_shift,y_test)) 

accuracies_LosReg = logRegres.score(X_test, y_test)
print(accuracies_LosReg_shift)
print(accuracies_LosReg)

[0.3920597505098392, 0.39595306830521493, 0.3699446460259025, 0.38040628227878276, 0.4304632253621845, 0.4170617368964695, 0.38244563921921765, 0.36941494292449084]
0.4304632253621845


TEST ACCURACY OF FEED FORWARD NEURAL NETWORK 

In [8]:
 # This model is without opeartor. It is similiarily to the classifier model but do not have encoder
modelWOoperator = FFNN(8,9)
modelWOoperator.load_state_dict(torch.load("modelwoOperator.pt")) # loaded from the file: parameters learned during training.
modelWOoperator.eval() # evaluation mode ensures consistent behavior during inference.


accuracies_ffnn = []
for i in range (-4, 4):
    X_test_shift = roll_data(X_test, i)
    test_shift_dataset = CustomSignalData(get_tensor(X_test_shift), get_tensor(y_test))
    testshiftloader = torch.utils.data.DataLoader(test_shift_dataset, batch_size=24, shuffle=True)
    accuracies_ffnn.append(clf_acc(modelWOoperator, testshiftloader, encoder = None))


In [9]:
print(accuracies_ffnn)

[0.6519059725910463, 0.6562526470862017, 0.6589898355541871, 0.6607157983349724, 0.6509529863220309, 0.6421113946159125, 0.6518742064395127, 0.6496876324639387]


In [10]:
test_dataset = CustomSignalData(get_tensor(X_test), get_tensor(y_test))
testloader = torch.utils.data.DataLoader(test_dataset, batch_size=24, shuffle=True)
accuracies_ffnn_single = clf_acc(modelWOoperator, testloader, encoder = None)
print(accuracies_ffnn_single)

0.6509529867385818


TEST ACCURACY OF SELF-SUPERVISED LEARNING

In [11]:
classifier = FFNN(8,9) # This indicates that the neural network expects input data with 8 features and will produce output predictions across 9 classes.
encoder = E(8,8)
encoder.load_state_dict(torch.load("encoder.pt")) # contains the learned parameters (weights and biases) of the encoder model
recovered_points_= torch.load("reference_points.pt") # These points represent reference points for inference or evaluation in the model
print(recovered_points_)
classifier.load_state_dict(torch.load("classifier.pt")) # contains the weights and biases learned during training.
classifier.eval() # sets the model to evaluation mode.
encoder.eval() # sets the model to evaluation mode.
# with torch.no_grad():
#     encoder.eval()
#     N_points = 1000
#     rand_idx = np.random.choice(all_X_test.shape[0], N_points)
#     y_tr = encoder(get_tensor(all_X_test[rand_idx]))
#     recovered_points_ = rotate_batch(y_tr,-all_shift_test[rand_idx].flatten(), 6)
#     del y_tr

accuracies_inferred_operator = []
for i in range (-4, 4):
    X_test_shift = roll_data(X_test, i)
    y1 = encoder(get_tensor(X_test_shift))
    y_tr_rotated = torch.zeros(X_test_shift.shape[0])
    for j, y_ in enumerate(y1):
        distances = np.zeros(8)
        for d in (range(-4,4)):
            x_rotated = used_bases[d].matmul(y_).repeat(N_points,1)
            distances[d] = ((x_rotated-recovered_points_)**2).mean(1).topk(2, largest=False)[0].mean()
        y_tr_rotated[j] = distances.argmin()
    y_tr_est1 = rotate_batch(y1, y_tr_rotated.int(),6)
    y_tr1 = classifier(y_tr_est1).argmax(1)
    # print(y_tr1- get_tensor(y_test).flatten())
    accuracies_inferred_operator.append((1-torch.abs(torch.sign(y_tr1- get_tensor(y_test).flatten()))).mean())

print(accuracies_inferred_operator)

tensor([[ 1.1943e-02,  7.0172e-03,  1.8266e-02,  ...,  1.5343e-02,
          2.2784e-03,  3.2136e-02],
        [ 1.1721e-01,  5.5396e-02,  1.8309e-01,  ...,  6.2217e-02,
          3.4511e-02,  4.1451e-02],
        [ 8.6316e-02,  3.0073e-02,  1.6398e-01,  ...,  5.3353e-02,
         -9.6507e-03,  1.6960e-01],
        ...,
        [ 1.7151e-02,  3.5203e-02,  3.3019e-04,  ...,  5.2602e-02,
          7.1660e-02,  2.5194e-02],
        [ 1.4617e-01,  2.4301e-01,  1.2075e-01,  ...,  4.0121e-02,
         -2.9864e-02,  2.1188e-01],
        [-5.6227e-02,  3.3742e-01,  3.7218e-01,  ...,  9.2131e-02,
         -7.3398e-02,  2.3686e-01]])
[tensor(0.6396), tensor(0.6405), tensor(0.6407), tensor(0.6405), tensor(0.6418), tensor(0.6410), tensor(0.6411), tensor(0.6409)]


In [12]:
# No need for shifting or rotating, directly use X_test
y1 = encoder(get_tensor(X_test))

# Calculate the rotated indices
y_tr_rotated = torch.zeros(X_test.shape[0])
for j, y_ in enumerate(y1):
    distances = np.zeros(8)
    for d in range(-4, 4):
        x_rotated = used_bases[d].matmul(y_).repeat(N_points, 1)
        distances[d] = ((x_rotated - recovered_points_)**2).mean(1).topk(2, largest=False)[0].mean()
    y_tr_rotated[j] = distances.argmin()

# Estimate rotated representations
y_tr_est1 = rotate_batch(y1, y_tr_rotated.int(), 6)

# Classify the rotated representations
y_tr1 = classifier(y_tr_est1).argmax(1)

# Calculate accuracy
accuracy = (1 - torch.abs(torch.sign(y_tr1 - get_tensor(y_test).flatten()))).mean()

print(accuracy)

tensor(0.6418)
