In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from joblib import dump, load
import matplotlib.pyplot as plt
import csv
import torch
import torch.nn as nn
import torch.optim as optim
from data_loader import CustomSignalData, CustomSignalData1
from torch.autograd import Variable
from encoder import Encoder as E
from helpers import set_cmd_cb, rms_formuula, get_data, get_all_data, get_shift_data, get_operators, plot_cfs_mat, roll_data



/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


DEFINF ESSENTIAL CLASSES, MODULES AND CPU

In [2]:
DEVICE = torch.device("cpu")
def getFeatureMatrix(rawDataMatrix, windowLength, windowOverlap):
    rms = lambda sig: np.sqrt(np.mean(sig**2))
    nChannels,nSamples = rawDataMatrix.shape    
    I = int(np.floor(nSamples/(windowLength-windowOverlap)))
    featMatrix = np.zeros([nChannels, I])
    for channel in range(nChannels):
        for i in range (I):
            wdwStrtIdx=i*(windowLength-windowOverlap)
            sigWin = rawDataMatrix[channel][wdwStrtIdx:(wdwStrtIdx+windowLength-1)] 
            featMatrix[channel, i] = rms(sigWin)
    featMatrixData = np.array(featMatrix)
    return featMatrixData

class FFNN(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(FFNN, self).__init__()
        self.encoder = torch.nn.Sequential(
            torch.nn.Linear(inputSize, 9, bias=False),
            torch.nn.Sigmoid()
        )
        self.classifer = torch.nn.Sequential(
            torch.nn.Linear(9, outputSize, bias=False),
            # torch.nn.Softmax(dim=1)
        )

    def forward(self, x, encoder=None):
        if not encoder:
            encoder = self.encoder
        z = encoder(x)
        class_z = self.classifer(z)

        return class_z

class Operator(nn.Module):
    def __init__(self, in_features, n_rotations):
        super(Operator, self).__init__()
        """
        Args:
          in_features (int): Number of input features which should be equal to xsize.
          out_features (out): Number of output features which should be equal to ysize.
        """
        self.in_features = in_features
        self.core = torch.nn.Parameter(torch.zeros(3*self.in_features**2)- 0*torch.diag(torch.rand(3*self.in_features**2)/10))
        self.core.requires_grad = True
        self.n_rotations = n_rotations
        
    def rotate_batch(self, x, d, out_features):
      rotated = torch.empty(x.shape[0], 3*out_features*out_features, device=DEVICE)
      phies = [torch.linalg.matrix_power(self.core,i).to(DEVICE) for i in range (0,self.n_rotations+0)]
      for i in range (x.shape[0]):
        rotated[i] = phies[(d[i]+0)%4].matmul(x[i]) 
      return rotated

    def forward(self, x, d):
        """
        Args:
          x of shape (batch_size, 3, xsize, xsize): Inputs.
        
        Returns:
          y of shape (batch_size, 3*xsize^2): Outputs.
        """
        z = self.rotate_batch(x, d, self.in_features)
        return z
def get_tensor(arr):
    return torch.tensor(arr, device=DEVICE,dtype=torch.float )

def rotate_batch(x, d, out_features):
    M = torch.diag(torch.ones(8)).roll(-1,1)
    used_bases = [torch.linalg.matrix_power(M,i).to(DEVICE) for i in range (8)]
    rotated = torch.empty(x.shape, device=DEVICE)
    for i in range (x.shape[0]):
        rotated[i] = used_bases[d[i]].matmul(x[i]) 
    return rotated

def clf_acc(model, loader, masks = None, encoder = None):
    model.eval()
    correct = 0
    iter = 0
    with torch.no_grad():
        for inputs, labels,_,_ in loader:
            inputs = inputs.to(DEVICE)
            if masks is not None:
                inputs = inputs * masks[:inputs.size()[0]]
            labels = labels.to(DEVICE)
            labels = labels.flatten()
            if encoder:
                pred = model(inputs, encoder)
            else:
                pred = model(inputs)
            correct += (1-torch.abs(torch.sign(torch.argmax(pred,dim = 1)- labels))).mean().item()
            iter += 1
    return correct/iter

def compute_accuracy(a, b, loader):
    a.eval()
    b.eval()
    
    correct = 0
    iter = 0
    
    with torch.no_grad():
        for inputs1, inputs2, shift1, shift2, labels, _ in loader:
            inputs1 = inputs1.to(DEVICE)
            inputs2 = inputs2.to(DEVICE)
            shift1 = -shift1.int().flatten().to(DEVICE)
            shift2 = -shift2.int().flatten().to(DEVICE)
            labels = labels.flatten().to(DEVICE)
            # zero the parameter gradients
            optimizer.zero_grad()
            
            # forward + backward + optimize
            y1 = a(inputs1)
            y_tr_est1 = rotate_batch(y1,shift1,6)
            y_tr1 = b(y_tr_est1)

            y2 = a(inputs2)
            y_tr_est2 = rotate_batch(y2,shift1,6)
            y_tr2 = b(y_tr_est2)

            correct += (1-torch.abs(torch.sign(torch.argmax(y_tr1,dim = 1)- labels))).mean().item() + \
                    (1-torch.abs(torch.sign(torch.argmax(y_tr2,dim = 1)- labels))).mean().item()
            iter += 1
    return correct * 0.5 / iter

LOAD DATA AND SEPERATE THE TRAIN AND TEST DATASET

In [3]:
subject = '26'

Fs = 1000
windowLength = int(np.floor(0.1*Fs))  #160ms
windowOverlap =  int(np.floor(50/100 * windowLength))

X_train = [np.zeros([0, 8])] * 3
y_train=[np.zeros([0])] * 3
X_test = [np.zeros([0, 8])] * 3
y_test=[np.zeros([0])] * 3
# X_train = np.zeros([0,8])
# y_train = np.zeros([0])
for k_fold in range(0,3):
    for shift in range(0,9): 
        for files in sorted(os.listdir(f'Subject_{subject}/Shift_{shift}/')):
            _, class_,_, rep_ = files.split('_')
            if int(class_) in [1,2,3,4,5,6,7,8,9]:
                df = pd.read_csv(f'Subject_{subject}/Shift_{shift}/{files}',skiprows=0,sep=' ',header=None)
                data_arr = np.stack([np.array(df.T[i::8]).T.flatten().astype('float32') for i in range (8)])
                data_arr -= 121
                data_arr /= 255.0
                feaData = getFeatureMatrix(data_arr, windowLength, windowOverlap)
                
                if not class_.startswith('9'):
                    rms_feature = feaData.sum(0)
                    baseline = 2*rms_feature[-50:].mean()
                    start_ = np.argmax(rms_feature[::1]>baseline)
                    end_  = -np.argmax(rms_feature[::-1]>baseline)
                    feaData = feaData.T[start_:end_]
                else:
                    feaData = feaData.T

                if rep_.startswith(str(k_fold+1)):
                    X_test[k_fold] = np.concatenate([X_test[k_fold],feaData])
                    y_test[k_fold] = np.concatenate([y_test[k_fold],np.ones_like(feaData)[:,0]*int(class_)-1])
                else:
                    X_train[k_fold] = np.concatenate([X_train[k_fold],feaData])
                    y_train[k_fold] = np.concatenate([y_train[k_fold],np.ones_like(feaData)[:,0]*int(class_)-1])


In [7]:
# 3-fold validation for 3 repetitions: 
# fold 1: train: rep 2, rep 3; test: rep 1
# fold 2: train: rep 1, rep 3; test: rep 2
# fold 3: train: rep 1, rep 1; test: rep 3
for i in range(3):
    print(X_train[i])
    print(X_train[i].shape)
    print(y_train[i])
    print(y_train[i].shape)
print("#############")
for i in range(3):
    print(X_test[i])
    print(X_test[i].shape)
    print(y_test[i])
    print(y_test[i].shape)

[[0.00800002 0.0031776  0.00327391 ... 0.02204677 0.00692822 0.00452824]
 [0.00784314 0.0031034  0.00315306 ... 0.02686469 0.00762216 0.00687193]
 [0.00729944 0.00267314 0.00292296 ... 0.02537185 0.00787279 0.00674646]
 ...
 [0.00804841 0.00336747 0.00332102 ... 0.00312833 0.00305294 0.00341329]
 [0.00771333 0.00315306 0.00320195 ... 0.0031034  0.00302739 0.0034585 ]
 [0.00760345 0.00357989 0.00311173 ... 0.00311173 0.00282385 0.00353989]]
(42004, 8)
[0. 0. 0. ... 8. 8. 8.]
(42004,)
[[0.00899624 0.00365503 0.00305294 ... 0.02290042 0.00879543 0.00738407]
 [0.01201943 0.00442413 0.00363372 ... 0.03947626 0.01278351 0.01073604]
 [0.01242612 0.00417111 0.00367622 ... 0.03907481 0.01230047 0.01338891]
 ...
 [0.00804841 0.00336747 0.00332102 ... 0.00312833 0.00305294 0.00341329]
 [0.00771333 0.00315306 0.00320195 ... 0.0031034  0.00302739 0.0034585 ]
 [0.00760345 0.00357989 0.00311173 ... 0.00311173 0.00282385 0.00353989]]
(41977, 8)
[0. 0. 0. ... 8. 8. 8.]
(41977,)
[[0.00899624 0.00365503 

SIMULATED SHIFT THE DATA

In [4]:
trainloader_list = []
alltrainloader_list = []
triplettrainloader_list = []

for k_fold in range(3):
    all_X_train, all_y_train, all_shift_train = get_all_data(X_train[k_fold], y_train[k_fold])
    all_X1_train, all_X2_train, all_shift_1_train, all_shift_2_train, all_y_shift_train = get_shift_data(all_X_train, all_shift_train, all_y_train)
    
    traindataset = CustomSignalData(get_tensor(X_train[k_fold]), get_tensor(y_train[k_fold]))
    trainloader = torch.utils.data.DataLoader(traindataset, batch_size = 1, shuffle=True)
    trainloader_list.append(trainloader)

    all_train_dataset = CustomSignalData(get_tensor(all_X_train), get_tensor(all_y_train))
    alltrainloader = torch.utils.data.DataLoader(all_train_dataset, batch_size = 102, shuffle=True)
    alltrainloader_list.append(alltrainloader)

    triplet_train_dataset = CustomSignalData1(get_tensor(all_X1_train), get_tensor(all_X2_train), get_tensor(all_shift_1_train), get_tensor(all_shift_2_train), get_tensor(all_y_shift_train))
    triplettrainloader = torch.utils.data.DataLoader(triplet_train_dataset, batch_size = 102, shuffle=True)
    triplettrainloader_list.append(triplettrainloader)



TRAIN LOGISTIC REGRESSION LEARNING MODEL

In [10]:
for k_fold in range(3):
    reg = LogisticRegression(penalty='l2', C=100).fit(X_train[k_fold], y_train[k_fold])
    dump(reg, f'LogisticRegression_fold_{k_fold+1}.joblib')

e:\python\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\python\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:

TEST ACCURACY OF LOGISTIC REGRESSION LEARNIGN MODEL

In [11]:
for k_fold in range(3):
    logRegres  = load(f'LogisticRegression_fold_{k_fold+1}.joblib')
    accuracies_LosReg_shift = []
    for i in range (-4, 4):
        X_test_shift = roll_data(X_test[k_fold], i)
        accuracies_LosReg_shift.append(logRegres.score(X_test_shift,y_test[k_fold]))
    print(f'Accuracy of {k_fold+1}:')
    print(accuracies_LosReg_shift)

Accuracy of 1:
[0.3940665839931317, 0.37579891252504055, 0.387150624821139, 0.3919202518363064, 0.41190498902985784, 0.35824668510922447, 0.38295335304779166, 0.35672040446437087]
Accuracy of 2:
[0.4008479016815129, 0.3988948697184776, 0.37393416853236794, 0.37107607297670653, 0.4197589672748059, 0.3798885342733292, 0.3887486304958796, 0.3550231029390749]
Accuracy of 3:
[0.4164009328447004, 0.3976012564846985, 0.3930798153348246, 0.3895102565322926, 0.4212079386987768, 0.3919375565180144, 0.3742325448574556, 0.38479843891295035]


TEST FEED FORAWRD NEURAL NETWORK LEARNING MODEL

In [5]:
accuracies_ffnn_list = []

for k_fold in range(3):
    modelWOoperator = FFNN(8,9)
    modelWOoperator.load_state_dict(torch.load(f"modelwoOperator_fold_{k_fold+1}.pt")) # loaded from the file: parameters learned during training.
    modelWOoperator.eval() # evaluation mode ensures consistent behavior during inference.


    accuracies_ffnn = []
    for i in range (-4, 4):
        X_test_shift = roll_data(X_test[k_fold], i)
        test_shift_dataset = CustomSignalData(get_tensor(X_test_shift), get_tensor(y_test[k_fold]))
        testshiftloader = torch.utils.data.DataLoader(test_shift_dataset, batch_size=24, shuffle=True)
        accuracies_ffnn.append(clf_acc(modelWOoperator, testshiftloader, encoder = None))

    print(accuracies_ffnn)
    accuracies_ffnn_list.append(accuracies_ffnn)

[0.6482919255437786, 0.6405415713991671, 0.6659924269609102, 0.6337310675898188, 0.6497493739190855, 0.6349978210655993, 0.6763648250965014, 0.6258921769172703]
[0.6602464988231659, 0.6571008402960641, 0.6689859940324511, 0.6611120451859065, 0.6582436982563564, 0.6694649872779846, 0.680263305595943, 0.6748543413025992]
[0.709362460734093, 0.6831067526993686, 0.6970345573882534, 0.6867735580154205, 0.6903668542022574, 0.6710945069789886, 0.6962821707469687, 0.6880448321093163]


TEST ACCURACY OF SELF-SUPERVISED LEARNING MODEL

In [6]:
DEVICE = torch.device("cpu") # operations is in CPU or GPU.
M = torch.diag(torch.ones(8)).roll(-1,1) # Create a diagnoise matrix then shift it to the right
used_bases = [torch.linalg.matrix_power(M,i).to(DEVICE) for i in range (8)] #

N_points = 1000

for k_fold in range(3):
    classifier = FFNN(8,9) # This indicates that the neural network expects input data with 8 features and will produce output predictions across 9 classes.
    encoder = E(8,8)
    encoder.load_state_dict(torch.load(f"encoder_fold_{k_fold+1}.pt")) # contains the learned parameters (weights and biases) of the encoder model
    recovered_points_= torch.load(f"reference_points_fold_{k_fold+1}.pt") # These points represent reference points for inference or evaluation in the model
    print(recovered_points_)
    classifier.load_state_dict(torch.load(f"classifier_fold_{k_fold+1}.pt")) # contains the weights and biases learned during training.
    classifier.eval() # sets the model to evaluation mode.
    encoder.eval() # sets the model to evaluation mode.
    # with torch.no_grad():
    #     encoder.eval()
    #     N_points = 1000
    #     rand_idx = np.random.choice(all_X_test.shape[0], N_points)
    #     y_tr = encoder(get_tensor(all_X_test[rand_idx]))
    #     recovered_points_ = rotate_batch(y_tr,-all_shift_test[rand_idx].flatten(), 6)
    #     del y_tr

    accuracies_inferred_operator = []
    for i in range (-4, 4):
        X_test_shift = roll_data(X_test[k_fold], i)
        y1 = encoder(get_tensor(X_test_shift))
        y_tr_rotated = torch.zeros(X_test_shift.shape[0])
        for j, y_ in enumerate(y1):
            distances = np.zeros(8)
            for d in (range(-4,4)):
                x_rotated = used_bases[d].matmul(y_).repeat(N_points,1)
                distances[d] = ((x_rotated-recovered_points_)**2).mean(1).topk(2, largest=False)[0].mean()
            y_tr_rotated[j] = distances.argmin()
        y_tr_est1 = rotate_batch(y1, y_tr_rotated.int(),6)
        y_tr1 = classifier(y_tr_est1).argmax(1)
        # print(y_tr1- get_tensor(y_test).flatten())
        accuracies_inferred_operator.append((1-torch.abs(torch.sign(y_tr1- get_tensor(y_test[k_fold]).flatten()))).mean())

    print(accuracies_inferred_operator)

tensor([[-0.0301,  0.1377,  0.4586,  ..., -0.0418,  0.0597,  0.3406],
        [ 0.0152,  0.1060, -0.0063,  ...,  0.0377,  0.0516,  0.0112],
        [ 0.1541,  0.3533,  0.0351,  ...,  0.0833,  0.3033, -0.0220],
        ...,
        [ 0.0659,  0.1611,  0.1938,  ...,  0.1494,  0.2227, -0.0730],
        [ 0.0005,  0.1235, -0.0265,  ...,  0.0201,  0.1384,  0.1979],
        [ 0.0354,  0.1446,  0.1430,  ...,  0.1763,  0.1053,  0.0076]])
[tensor(0.6720), tensor(0.6732), tensor(0.6697), tensor(0.6729), tensor(0.6717), tensor(0.6738), tensor(0.6731), tensor(0.6728)]
tensor([[ 0.0902,  0.0697,  0.0567,  ...,  0.4172, -0.0116,  0.0039],
        [ 0.0302,  0.0029,  0.2069,  ..., -0.0264,  0.3268,  0.0334],
        [ 0.0175,  0.0196,  0.0059,  ...,  0.0103,  0.0163,  0.0169],
        ...,
        [ 0.0161,  0.0098,  0.0082,  ...,  0.0117,  0.0091,  0.0120],
        [ 0.4702, -0.0584,  0.1038,  ...,  0.0598,  0.3008,  0.1470],
        [ 0.0143,  0.0329,  0.1210,  ..., -0.0186,  0.2466,  0.0175]])
[te